# Numpy Set Operations

## What is a Set?
A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

## Creat Sets in Numpy
We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

In [1]:
import numpy as np

- Convert following array with repeated elements to a set:

In [2]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


## Finding Union
To find the unique values of two arrays, use the union1d() method.

- Find union of the following two set arrays:

In [3]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


## Finding Intersection
To find only the values that are present in both arrays, use the intersect1d() method.

- Find intersection of the following two set arrays:

In [4]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


## Finding Difference
To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

- Find the difference of the set1 from set2:

In [5]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(arr1, arr2, assume_unique=True)

print(newarr)

[1 2]


## Finding Symmetric Difference
To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

- Find the symmetric difference of the set1 and set2:

In [6]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(arr1, arr2, assume_unique=True)

print(newarr)

[1 2 5 6]
