# NumPy Filter Array

## Filtering Arrays
- Getting some elements out of an existing array and creating a new array out of them is called filtering.

- In NumPy, you filter an array using a boolean index list.

- *A boolean index list is a list of booleans corresponding to indexes in the array.*

In [1]:
import numpy as np

- Create an array from the elements on index 0 and 2:

In [2]:
arr = np.array([41, 42,43, 44])
x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]


- The example above will return [41, 43], why?

- Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

## Creating the Filter Array
- In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

- Create a filter array that will return only values higher than 42:

In [ ]:
arr = np.array([41, 42, 43, 44, 45])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
    # if the element is higher than 42, set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True, True]
[43 44 45]


- Create a filter array that will return only even elements from the original array:

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
    # if the element is completely divisble by 2, set the value to True, otherwise False
    if element %2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True]
[2 4 6 8]


## Creating Filter Directly From Array
- The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

- We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

- Create a filter array that will return only values higher than 42:

In [11]:
arr = np.array([41, 42, 43, 44, 45])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True  True]
[43 44 45]


- Create a filter array that will return only even elements from the original array:

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

filter_arr = arr %2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False  True]
[2 4 6 8]
