## NumPy Creating Arrays

In [1]:
import numpy as np

## Creat a NumPy ndarray Object
- NumPy is used to work with arrays. The array object in NumPy is called ndarray.

- We can create a NumPy ndarray object by using the array() function.

- Use a tuple to create a NumPy array:

In [3]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## Dimension in Arrays
- A dimension in arrays is one level of array depth (nested arrays).

## 0-D Arrays
- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

- Create a 0-D array with value 45

In [6]:
arr = np.array(45)

print(arr)

45


## 1-D Arrays
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

    
    - These are the most common and basic arrays

- Create a 1-D array containing the values 1,2,3,4,5:

In [7]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


## 2-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D array.

    - These are often used to represent matrix or 2nd order tensors

- Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D Arrays
- An array that has 2-D arrays (matrices) as its elements is called 3-D array.

    - These are often used to represent a 3rd order tensor.

- Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [ ]:
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions
- NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays
- An array can have any number of dimensions.

- When the array is created, you can define the number of dimensions by using the ndmin argument.

In [18]:
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5
