# Random Numbers in NumPy

## What is a Random Number?
- Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

## Generate Random Number
- NumPy offers the random module to work with random numbers.

- Generate a random integer from 0 to 100:

In [1]:
from numpy import random

In [4]:
x = random.randint(100)

print(x)

83


## Generate Random Float
- The random module's rand() method returns a random float between 0 and 1.

- Generate a random float from 0 to 1:

In [5]:
x = random.rand()

print(x)

0.21786349578824027


## Genarate Random Array
- In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

### Integers
- The randint() method takes a size parameter where you can specify the shape of an array.

- Generate a 1-D array containing 5 random integers from 0 to 100:

In [6]:
x = random.randint(100, size=(5))

print(x)

[62  8 56  7 13]


- Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [8]:
x = random.randint(100, size=(3, 5))

print(x)

[[ 2 38 70 28 66]
 [24 77 35 35 90]
 [95 57 47 93 66]]


### Float
- The rand() method also allows you to specify the shape of the array.

- Generate a 1-D array containing 5 random floats:

In [9]:
x = random.rand(5)

print(x)

[0.69205728 0.35899837 0.67422369 0.86131626 0.03689512]


- Generate a 2-D array with 3 rows, each row containing 5 random numbers:

In [10]:
x = random.rand(3, 5)

print(x)

[[5.56448318e-01 3.85076535e-01 7.03799720e-01 5.08806304e-01
  2.62403702e-01]
 [2.65116474e-01 6.62414745e-01 6.87208263e-01 1.06705364e-01
  8.96070964e-01]
 [1.33393516e-01 5.60916183e-01 1.90791472e-04 2.69841136e-01
  4.28021989e-01]]


## Generate Random Number From Array
- The choice() method allows you to generate a random value based on an array of values.

- The choice() method takes an array as a parameter and randomly returns one of the values.

- Return one of the values in an array:

In [12]:
x = random.choice([3, 5, 7, 9])

print(x)

7


- The choice() method also allows you to return an array of values.

- Add a size parameter to specify the shape of the array.

- Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

In [14]:
x = random.choice([3, 5, 6, 9], size=(3, 5))

print(x)

[[5 3 6 3 3]
 [5 6 5 5 3]
 [5 6 5 9 3]]
