# Random Data Distribution

## What is Data Distribution?
- Data Distribution is a list of all possible values, and how often each value occurs.

- Such lists are important when working with statistics and data science.

- The random module offer methods that returns randomly generated data distributions.

In [1]:
from numpy import random

- Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

- The probability for the value to be 3 is set to be 0.1

- The probability for the value to be 5 is set to be 0.3

- The probability for the value to be 7 is set to be 0.6

- The probability for the value to be 9 is set to be 0

In [3]:
x = random.choice([2, 4, 6, 8], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[2 4 4 6 6 6 4 6 6 4 6 6 2 6 4 4 4 6 6 6 4 4 6 6 2 6 6 4 6 6 6 6 6 4 4 4 6
 6 2 6 6 6 6 4 4 6 4 6 2 4 6 6 6 4 4 4 4 6 4 6 6 6 6 2 4 4 6 6 6 2 4 6 4 4
 6 6 6 6 6 4 4 6 6 6 6 6 4 6 6 4 4 6 2 6 4 6 4 6 4 4]


- Even if you run the example above 100 times, the value 9 will never occur.

- You can return arrays of any shape and size by specifying the shape in the size parameter.

- Same example as above, but return a 2-D array with 3 rows, each containing 5 values

In [5]:
x = random.choice([2, 4, 6, 8], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[2 6 6 6 6]
 [6 6 4 2 6]
 [4 6 2 4 4]]
